
jobs:
- job: Windows_Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - bash: echo "Hello world"
- job: Linux_Build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: echo "Hello world"
- job: OSX_Build
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: echo "Hello world"
