
trigger:
  - master
jobs:
- job: Windows_Build
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - bash: echo "Hello world"
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: pip install pyinstaller
    displayName: 'Install PyInstaller'
- job: Linux_Build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: echo "Hello world"
- job: OSX_Build
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: echo "Hello world"
